---
title: "Class 26 code"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}

library(SDS100)


```






$\\$








# Multiple regression



Try to predict a movie's revenue (domgross_2013) from:
  1) year
  2) whether it passed the Bechdel test
  3) the movie's budget

```{r}



# load the library with the data
library(fivethirtyeight)

# remove missing values
bechdel <- na.omit(bechdel)


columns_to_use <- c("year", "binary", "budget_2013", "domgross_2013")

bechdel2 <- bechdel[, columns_to_use]



# fit a multiple regression model




# print regression coefficients, standard errors, etc. 







```









$\\$






# Inference for correlation - Bechdel data


We can run a parametric test for correlation using the following t-statistic:

$t ~=~ \frac{r\sqrt{n - 2}}{\sqrt{1 - r^2}}$


Let's examine again if there is a correlation between budget and revenue on the Bechdel data.



$\\$



Step 1:






```{r}


# extract variables of interest
budget <- bechdel$budget/10^6
revenue <- bechdel$domgross/10^6




# Step 2 - calculate the t-statistic








# Steps 3-5: 









# check with the cor.test() function 



```








